### ISSUE TITLE
PHP instruction and flags

### ISSUE THREAD

**Issue by benb123** [visrealm/vrEmu6502#3]
Hi,

First I love this emulator. Nice and clearly written. I noticed these debugging my C64 emulation:

1. The PHP instruction was causing my C64 emulation to freeze on the first IRQ:

  // Ben - Why alter the BRK and Undefined status bits? I checked some write ups and couldn't see this specified?
  //push(vr6502, vr6502->flags | 0x30);
  push(vr6502, vr6502->flags);

2. Also is there any reason why Flags is not cleared in vrEmu6502Reset fn? I mean it just means we can rely on a defined state of things but perhaps the real processors make no guarantees?

    vr6502->flags = 0;

Thanks,

Ben

**Comment by visrealm** [comment]
Hi Ben. Thanks for your bug report.

I think the issue is actually in PLP.  According to a number of sources, eg. [https://www.masswerk.at/6502/6502_instruction_set.html](https://www.masswerk.at/6502/6502_instruction_set.html), BRK and BIT 5 are always set when pushed on to the stack since they don't represent any hardware bit. However, PLP will ignore those bits (again, there is no hardware to pull to). So, I believe the fix should be to bitwise-and with 0xcf in plp().

Regarding reset, the original 6502 starts with the flags in an undefined state. The 65C02 however does have a known state for some of the bits. Given the 6502's starting state is undefined, it's probably best to leave it undefined (except perhaps Bits 4 and 5) . I'll add code for the 65C02's though.

**Comment by visrealm** [comment]
Hi Ben,

I've pushed two fixes now. The flags fix isn't exactly as I described earlier. After further consideration, I've now made the fix within beginInterupt(). I believe php() and plp() are correct. 

Can you try the updated version in your emulator and report back?

Cheers
Troy

**Comment by benb123** [comment]
Hi Troy,

Thanks for your rapid fix. Much appreciated. I refreshed my "hacks" with your thought-thru solutions and the C64 booted up without issue so I believe you must be either completely correct or close enough! :-)

Cheers,

Ben

**Comment by visrealm** [comment]
Nice. Thanks.
